### ISSUE TITLE
Overestimating handsontools and outdoors_everyday

### ISSUE THREAD

**Issue by mfasules** [jdingel/DingelNeiman-workathome#1]
I discovered a possible overestimation of the variables handsontools and outdoors_everyday in onet_characteristics.do. 

In line 40, you keep the percent distribution "CXP" scaleid for elementid ("4.C.2.d.1.g","4.C.2.a.1.c","4.C.2.a.1.d")

https://github.com/jdingel/DingelNeiman-workathome/blob/35dad0b76425212847a25ec03bea2a2be7d3bf8e/occ_onet_scores/code/onet_characteristics.do#L40

But then, you use the same average "CX" methodology to define handsontools and outdoors_everyday in lines 46 and 48.

https://github.com/jdingel/DingelNeiman-workathome/blob/35dad0b76425212847a25ec03bea2a2be7d3bf8e/occ_onet_scores/code/onet_characteristics.do#L46

I believe you are counting some occupations where the average data value (CX) is less than 4.5, but some of the CXP data values happen to be between 4.5 and 5. 

For example, O.NET.SOC.Code "11-3071.01" is classified as outdoors_everyday == 1, but the CX data value for "4.C.2.a.1.c" is 3.18, and the data value for "4.C.2.a.1.d" is 2.04.

For "4.C.2.a.1.d", the "CXP" data value for category 5 is 4.8, which is why I think this is defining outdoors_everyday == 1 when it should be 0.

**Comment by jdingel** [comment]
You are absolutely right. Thank you for pointing this out. We will correct this shortly. Could you please share your name with us here or via email so that we can acknowledge your very helpful feedback in the updated version of our note?

**Comment by jdingel** [comment]
Thanks very much. Commit [755ea29](https://github.com/jdingel/DingelNeiman-workathome/commit/755ea29fc27021a7b1cc523d7612caf6de0a38c4) corrects this mistake.

The correction raised our estimate of the share of U.S. jobs that can be done at home from 34 to 37 percent and raised our estimate of the share of the wage bill represented by these jobs from 44 to 46 percent. Similarly, the correction increased these shares for nearly all geographies and industries by a few percentage points.
